cors:
  originPatterns: http://localhost:3000,http://localhost:8080
file:
  upload-dir: /Workspace Intellij/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-restful?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  devtools:
    restart:
      log-condition-evaluation-delta: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true